# Generated by Django 2.2 on 2019-04-21 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-created'], 'verbose_name': 'Journal Entry', 'verbose_name_plural': 'Journal Entries'},
        ),
    ]
